# Generated by Django 5.0 on 2023-12-08 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=50)),
                ('player2', models.CharField(max_length=50)),
                ('current_player', models.CharField(max_length=50)),
                ('board', models.CharField(default='         ', max_length=9)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('is_draw', models.BooleanField(default=False)),
                ('moves', models.IntegerField(default=0)),
                ('played_date', models.DateTimeField(auto_now_add=True)),
                ('game_state', models.TextField(default='')),
                ('log', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
